name: Build Documentation

on:
  push:
    branches: [ master ]
    paths:
      - 'docs/**'
      - '.github/workflows/docs.yml'

jobs:
  mkdocs-build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: "3.8"
    - name: Prepare build environment
      run: |
        python -m pip install --upgrade pip setuptools wheel
        pip install mkdocs mkdocs-material mkdocs-git-revision-date-localized-plugin Markdown markdown-include MarkupSafe pymdown-extensions PyYAML
    - name: Build documentation
      run: mkdocs gh-deploy