name: Publish

on:
  release:
    types: [ published ]

jobs:
  grm:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install GitReleaseManager
      uses: gittools/actions/gitreleasemanager/setup@v0.9.13
      with:
        versionSpec: '0.10.x'
    - name: Close milestone with GitReleaseManager
      uses: gittools/actions/gitreleasemanager/close@v0.9.13
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        owner: ${{ github.repository_owner }}
        repository: ${{ github.event.repository.name }}
        milestone: ${{ github.event.release.tag_name }}
  psgallery:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set environment variables
      run: |
        Add-Content -Path $env:GITHUB_ENV -Value "PROJECT_NAME=${{ github.event.repository.name }}"
        Add-Content -Path $env:GITHUB_ENV -Value "PROJECT_NAME=${{ github.event.repository.name }}"
        Add-Content -Path $env:GITHUB_ENV -Value "RELEASE_NOTES=${{ github.event.release.body }}"
        Add-Content -Path $env:GITHUB_ENV -Value "RELEASE_VERSION=${{ github.event.release.tag_name }}"
      shell: pwsh
    - name: Publish package to PowerShell Gallery
      run: .github\workflows\psgallery-publish.ps1
      shell: pwsh
