name: Publish

on:
  release:
    types: [ published ]

jobs:
  grm:
    runs-on: ubuntu-latest
    steps:
    - name: Install GitReleaseManager
      uses: gittools/actions/gitreleasemanager/setup@v0.9.2
      with:
        versionSpec: '0.10.x'
    - name: Close milestone with GitReleaseManager
      uses: gittools/actions/gitreleasemanager/close@v0.9.2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        owner: ${{ github.repository_owner }}
        repository: ${{ github.event.repository.name }}
        milestone: ${{ github.event.release.tag_name }}
    - name: Export release notes for use in PSD1 file
      uses: gittools/actions/gitreleasemanager/export@v0.9.2
  psgallery:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Publish package to PowerShell Gallery
      env:
        PSGALLERY_APIKEY: ${{ secrets.PSGALLERY_APIKEY }}
        PROJECT_NAME: ${{ github.event.repository.name }}
        RELEASE_NOTES: ${{ github.event.release.body }}
        RELEASE_VERSION: ${{ github.event.release.tag_name }}
      run: .github\workflows\psgallery-publish.ps1
      shell: pwsh
