name: Release

on:
  push:
    branches: [ master ]
    paths:
    - 'PsLogLite/**'
    - '.github/workflows/release.yml'

jobs:
  release:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Fetch all history for all tags and branches
      run: git fetch --prune --unshallow
    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v0.9.13
      with:
        versionSpec: '5.x'
    - name: Use GitVersion
      id: gitversion
      uses: gittools/actions/gitversion/execute@v0.9.13
    - name: Install GitReleaseManager
      uses: gittools/actions/gitreleasemanager/setup@v0.9.13
      with:
        versionSpec: '0.10.x'
    - name: Set environment variables
      run: |
        echo PROJECT_NAME=${{ github.event.repository.name }} >> $GITHUB_ENV
        echo RELEASE_VERSION=${{ steps.gitversion.outputs.semVer }} >> $GITHUB_ENV
      shell: powershell
    - name: Create artifact
      run: .github\workflows\create-artifact.ps1
      shell: powershell
    - name: Create release
      uses: gittools/actions/gitreleasemanager/create@v0.9.13
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        owner: ${{ github.repository_owner }}
        repository: ${{ github.event.repository.name }}
        milestone: ${{ steps.gitversion.outputs.semVer }}
        name: ${{ steps.gitversion.outputs.semVer }}
        assets: |
          ${{ github.event.repository.name }}-${{ steps.gitversion.outputs.semVer }}.zip
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: install-archive
        path: |
          ${{ github.event.repository.name }}-${{ steps.gitversion.outputs.semVer }}.zip
