name: Release

on:
  push:
    branches: [ master ]
    paths:
    - 'PsLogLite/**'
    - '.github/workflows/release.yml'

jobs:
  release:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Fetch all history for all tags and branches
      run: git fetch --prune --unshallow
    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v0.9.2
      with:
        versionSpec: '5.2.x'
    - name: Use GitVersion
      id: gitversion
      uses: gittools/actions/gitversion/execute@v0.9.2
    - name: Install GitReleaseManager
      uses: gittools/actions/gitreleasemanager/setup@v0.9.2
      with:
        versionSpec: '0.10.x'
    - name: Create artifacts
      env:
        SEMVER: ${{ steps.gitversion.outputs.semVer }}
      run: |
        Compress-Archive -Path .\PsLogLite -DestinationPath ".\PsLogLite-$($Env:SEMVER).zip" -CompressionLevel Optimal
        tar -czvf "PsLogLite-$($Env:SEMVER).tar.gz" .\PsLogLite
      shell: powershell
    - name: Create release
      uses: gittools/actions/gitreleasemanager/create@v0.9.2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        owner: ${{ github.repository_owner }}
        repository: ${{ github.event.repository.name }}
        milestone: ${{ steps.gitversion.outputs.semVer }}
        name: ${{ steps.gitversion.outputs.semVer }}
        assets: |
          PsLogLite-${{ steps.gitversion.outputs.semVer }}.zip
          PsLogLite-${{ steps.gitversion.outputs.semVer }}.tar.gz